name: agents

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  agents-updater:
    uses: Mindgames/changelog-agent/.github/workflows/agents-codex.yml@main
    secrets: inherit
    with:
      mode: suggest
      always_include: "xyz"
      model: gpt-5-codex
